name: Build and Run Wax Targets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - name: Install GCC
        run: sudo apt-get install gcc g++

      - name: Install Java
        run: sudo apt-get install default-jdk

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"

      - name: Install Swift
        run: sudo apt-get install swift

      - name: Install Lua
        run: sudo apt-get install lua5.3

      - name: Install wabt
        run: |
          sudo apt-get update
          sudo apt-get install wabt

      - name: Install binaryen
        run: |
          sudo apt-get update
          sudo apt-get install binaryen

      - name: Create build directory
        run: mkdir build

      - name: Run CMake
        run: cmake -S . -B build -GNinja

      - name: Build with Ninja
        run: cmake --build build

      - name: List build directory contents
        run: ls build

      - name: Transpile to C and check output
        run: |
          cd build
          ./waxc ../examples/fib.wax --c fib.c --ast
          gcc fib.c -o fib
          OUTPUT=$(./fib 9)
          echo "Output: $OUTPUT"
          if [ "$OUTPUT" -eq 34 ]; then
            echo "C Output is correct."
          else
            echo "C Output is incorrect."
            exit 1
          fi

      - name: Transpile to Java and check output
        run: |
          cd build
          ./waxc ../examples/fib.wax --java fib.java
          javac fib.java
          OUTPUT=$(java fib 9)
          echo "Output: $OUTPUT"
          if [ "$OUTPUT" -eq 34 ]; then
            echo "Java Output is correct."
          else
            echo "Java Output is incorrect."
            exit 1
          fi

      - name: Transpile to TypeScript and check output
        run: |
          cd build
          ./waxc ../examples/fib.wax --ts fib.ts
          npm install -g typescript
          tsc fib.ts
          OUTPUT=$(node fib.js 9)
          echo "Output: $OUTPUT"
          if [ "$OUTPUT" -eq 34 ]; then
            echo "TypeScript Output is correct."
          else
            echo "TypeScript Output is incorrect."
            exit 1
          fi

      - name: Transpile to Python and check output
        run: |
          cd build
          ./waxc ../examples/fib.wax --py fib.py
          OUTPUT=$(python3 fib.py 9)
          echo "Output: $OUTPUT"
          if [ "$OUTPUT" -eq 34 ]; then
            echo "Python Output is correct."
          else
            echo "Python Output is incorrect."
            exit 1
          fi

      - name: Transpile to C# and check output
        run: |
          cd build
          ./waxc ../examples/fib.wax --cs fib.cs
          dotnet new console -n FibApp
          mv fib.cs FibApp/Program.cs
          cd FibApp
          dotnet run 9 > output.txt
          OUTPUT=$(grep -Eo '^[0-9]+$' output.txt)
          echo "Output: $OUTPUT"
          if [ "$OUTPUT" == "34" ]; then
            echo "C# Output is correct."
          else
            echo "C# Output is incorrect."
            exit 1
          fi

      - name: Transpile to C++ and check output
        run: |
          cd build
          ./waxc ../examples/fib.wax --cpp fib.cpp
          g++ fib.cpp -o fib_cpp
          OUTPUT=$(./fib_cpp 9)
          echo "Output: $OUTPUT"
          if [ "$OUTPUT" -eq 34 ]; then
            echo "C++ Output is correct."
          else
            echo "C++ Output is incorrect."
            exit 1
          fi

      - name: Transpile to Swift and check output
        run: |
          cd build
          ./waxc ../examples/fib.wax --swift fib.swift
          swiftc fib.swift -o fib_swift
          OUTPUT=$(./fib_swift 9)
          echo "Output: $OUTPUT"
          if [ "$OUTPUT" -eq 34 ]; then
            echo "Swift Output is correct."
          else
            echo "Swift Output is incorrect."
            exit 1
          fi

      - name: Transpile to Lua and check output
        run: |
          cd build
          ./waxc ../examples/fib.wax --lua fib.lua
          OUTPUT=$(lua fib.lua 9)
          echo "Output: $OUTPUT"
          if [ "$OUTPUT" -eq 34 ]; then
            echo "Lua Output is correct."
          else
            echo "Lua Output is incorrect."
            exit 1
          fi

      - name: Transpile to WebAssembly Text Format (wat)
        run: |
          cd build
          ./waxc ../examples/fib.wax --wat fib.wat

      - name: Compile wat to wasm
        run: |
          cd build
          wat2wasm fib.wat -o fib.wasm

      - name: Optimize wasm
        run: |
          cd build
          wasm-opt fib.wasm -o fib.O4.wasm -O4

      - name: Run WebAssembly in Node.js
        run: |
          cd build
          echo 'const fs = require("fs");' > run_wasm.js
          echo 'const bytes = fs.readFileSync("fib.O4.wasm");' >> run_wasm.js
          echo 'const importObject = { console: { log: console.log }, Math };' >> run_wasm.js
          echo 'WebAssembly.instantiate(bytes, importObject).then(obj => {' >> run_wasm.js
          echo '  const result = obj.instance.exports.fib(9);' >> run_wasm.js
          echo '  console.log("Output:", result);' >> run_wasm.js
          echo '  if (result === 34) {' >> run_wasm.js
          echo '    console.log("WebAssembly Output is correct.");' >> run_wasm.js
          echo '  } else {' >> run_wasm.js
          echo '    console.log("WebAssembly Output is incorrect.");' >> run_wasm.js
          echo '    process.exit(1);' >> run_wasm.js
          echo '  }' >> run_wasm.js
          echo '});' >> run_wasm.js
          node run_wasm.js

      - name: Transpile to JSON
        run: |
          cd build
          ./waxc ../examples/fib.wax --json fib.json
          cat fib.json
